export default function Head() {
  return (
    <>
      <title>The Spiral Staircase</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
       <link rel="preload" href="style.css" as="style" />

    </>
  );
}
